[window]
opacity = 0.5

[font]
normal = { family = "0xProtoNerdFont", style = "Regular" }
bold = { family = "0xProtoNerdFont", style = "Bold" }
italic = { family = "0xProtoNerdFont", style = "Italic" }
bold_italic = { family = "0xProtoNerdFont", style = "Bold Italic" }
